// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(yooz_text_cleanupFFI)
import yooz_text_cleanupFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_yooz_text_cleanup_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_yooz_text_cleanup_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}


/**
 * Rule information for API queries
 */
public struct RuleInfo {
    public var id: String
    public var name: String
    public var category: String
    public var isPicky: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, name: String, category: String, isPicky: Bool) {
        self.id = id
        self.name = name
        self.category = category
        self.isPicky = isPicky
    }
}



extension RuleInfo: Equatable, Hashable {
    public static func ==(lhs: RuleInfo, rhs: RuleInfo) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.name != rhs.name {
            return false
        }
        if lhs.category != rhs.category {
            return false
        }
        if lhs.isPicky != rhs.isPicky {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(name)
        hasher.combine(category)
        hasher.combine(isPicky)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRuleInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RuleInfo {
        return
            try RuleInfo(
                id: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                category: FfiConverterString.read(from: &buf), 
                isPicky: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: RuleInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.category, into: &buf)
        FfiConverterBool.write(value.isPicky, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRuleInfo_lift(_ buf: RustBuffer) throws -> RuleInfo {
    return try FfiConverterTypeRuleInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRuleInfo_lower(_ value: RuleInfo) -> RustBuffer {
    return FfiConverterTypeRuleInfo.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Rule categories for text cleanup
 *
 * Categories allow selective application of rules based on:
 * - Performance requirements (fewer categories = faster)
 * - Monetization tiers (free/pro/premium)
 * - User preferences (keep informal speech, etc.)
 */

public enum Category {
    
    /**
     * Common typos and obvious fixes (e.g., alot → a lot)
     */
    case basic
    /**
     * Subject-verb agreement (e.g., I are → I am)
     */
    case grammar
    /**
     * Article corrections (e.g., a apple → an apple)
     */
    case articles
    /**
     * Spoken to formal (e.g., gonna → going to)
     */
    case informal
    /**
     * Irregular verb corrections (e.g., I seen → I saw)
     */
    case verbs
    /**
     * Number formatting (e.g., twenty three → 23)
     */
    case numbers
    /**
     * Capitalization and punctuation
     */
    case punctuation
    /**
     * Redundancy and wordiness
     */
    case style
    /**
     * Complex grammar and nuanced corrections
     */
    case advanced
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCategory: FfiConverterRustBuffer {
    typealias SwiftType = Category

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Category {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .basic
        
        case 2: return .grammar
        
        case 3: return .articles
        
        case 4: return .informal
        
        case 5: return .verbs
        
        case 6: return .numbers
        
        case 7: return .punctuation
        
        case 8: return .style
        
        case 9: return .advanced
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Category, into buf: inout [UInt8]) {
        switch value {
        
        
        case .basic:
            writeInt(&buf, Int32(1))
        
        
        case .grammar:
            writeInt(&buf, Int32(2))
        
        
        case .articles:
            writeInt(&buf, Int32(3))
        
        
        case .informal:
            writeInt(&buf, Int32(4))
        
        
        case .verbs:
            writeInt(&buf, Int32(5))
        
        
        case .numbers:
            writeInt(&buf, Int32(6))
        
        
        case .punctuation:
            writeInt(&buf, Int32(7))
        
        
        case .style:
            writeInt(&buf, Int32(8))
        
        
        case .advanced:
            writeInt(&buf, Int32(9))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCategory_lift(_ buf: RustBuffer) throws -> Category {
    return try FfiConverterTypeCategory.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCategory_lower(_ value: Category) -> RustBuffer {
    return FfiConverterTypeCategory.lower(value)
}



extension Category: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Supported languages for text cleanup
 *
 * Each language has its own set of grammar rules.
 */

public enum Language {
    
    /**
     * English (generic)
     */
    case english
    /**
     * English (US)
     */
    case englishUs
    /**
     * English (GB/UK)
     */
    case englishGb
    /**
     * Spanish
     */
    case spanish
    /**
     * French
     */
    case french
    /**
     * German
     */
    case german
    /**
     * Portuguese
     */
    case portuguese
    /**
     * Italian
     */
    case italian
    /**
     * Dutch
     */
    case dutch
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLanguage: FfiConverterRustBuffer {
    typealias SwiftType = Language

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Language {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .english
        
        case 2: return .englishUs
        
        case 3: return .englishGb
        
        case 4: return .spanish
        
        case 5: return .french
        
        case 6: return .german
        
        case 7: return .portuguese
        
        case 8: return .italian
        
        case 9: return .dutch
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Language, into buf: inout [UInt8]) {
        switch value {
        
        
        case .english:
            writeInt(&buf, Int32(1))
        
        
        case .englishUs:
            writeInt(&buf, Int32(2))
        
        
        case .englishGb:
            writeInt(&buf, Int32(3))
        
        
        case .spanish:
            writeInt(&buf, Int32(4))
        
        
        case .french:
            writeInt(&buf, Int32(5))
        
        
        case .german:
            writeInt(&buf, Int32(6))
        
        
        case .portuguese:
            writeInt(&buf, Int32(7))
        
        
        case .italian:
            writeInt(&buf, Int32(8))
        
        
        case .dutch:
            writeInt(&buf, Int32(9))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLanguage_lift(_ buf: RustBuffer) throws -> Language {
    return try FfiConverterTypeLanguage.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLanguage_lower(_ value: Language) -> RustBuffer {
    return FfiConverterTypeLanguage.lower(value)
}



extension Language: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Rule strictness level
 *
 * Controls which rules within a category are applied.
 */

public enum Level {
    
    /**
     * Only critical rules (~20% of rules)
     */
    case essential
    /**
     * Default rules (~60% of rules)
     */
    case standard
    /**
     * Include picky/strict rules (100% of rules)
     */
    case thorough
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLevel: FfiConverterRustBuffer {
    typealias SwiftType = Level

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Level {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .essential
        
        case 2: return .standard
        
        case 3: return .thorough
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Level, into buf: inout [UInt8]) {
        switch value {
        
        
        case .essential:
            writeInt(&buf, Int32(1))
        
        
        case .standard:
            writeInt(&buf, Int32(2))
        
        
        case .thorough:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLevel_lift(_ buf: RustBuffer) throws -> Level {
    return try FfiConverterTypeLevel.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLevel_lower(_ value: Level) -> RustBuffer {
    return FfiConverterTypeLevel.lower(value)
}



extension Level: Equatable, Hashable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeRuleInfo: FfiConverterRustBuffer {
    typealias SwiftType = [RuleInfo]

    public static func write(_ value: [RuleInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeRuleInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [RuleInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [RuleInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeRuleInfo.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeCategory: FfiConverterRustBuffer {
    typealias SwiftType = [Category]

    public static func write(_ value: [Category], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeCategory.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Category] {
        let len: Int32 = try readInt(&buf)
        var seq = [Category]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeCategory.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeLanguage: FfiConverterRustBuffer {
    typealias SwiftType = [Language]

    public static func write(_ value: [Language], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeLanguage.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Language] {
        let len: Int32 = try readInt(&buf)
        var seq = [Language]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeLanguage.read(from: &buf))
        }
        return seq
    }
}
/**
 * Correct grammar with default settings (English, all categories, standard level)
 */
public func correctGrammar(text: String) -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_yooz_text_cleanup_fn_func_correct_grammar(
        FfiConverterString.lower(text),$0
    )
})
}
/**
 * Correct grammar for a specific language
 */
public func correctGrammarForLanguage(text: String, language: Language) -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_yooz_text_cleanup_fn_func_correct_grammar_for_language(
        FfiConverterString.lower(text),
        FfiConverterTypeLanguage.lower(language),$0
    )
})
}
/**
 * Correct grammar with category filtering
 */
public func correctGrammarWithCategories(text: String, language: Language, categories: [Category]) -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_yooz_text_cleanup_fn_func_correct_grammar_with_categories(
        FfiConverterString.lower(text),
        FfiConverterTypeLanguage.lower(language),
        FfiConverterSequenceTypeCategory.lower(categories),$0
    )
})
}
/**
 * Correct grammar with full options (categories and level)
 */
public func correctGrammarWithOptions(text: String, language: Language, categories: [Category], level: Level) -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_yooz_text_cleanup_fn_func_correct_grammar_with_options(
        FfiConverterString.lower(text),
        FfiConverterTypeLanguage.lower(language),
        FfiConverterSequenceTypeCategory.lower(categories),
        FfiConverterTypeLevel.lower(level),$0
    )
})
}
/**
 * Get all categories
 */
public func getAllCategories() -> [Category] {
    return try!  FfiConverterSequenceTypeCategory.lift(try! rustCall() {
    uniffi_yooz_text_cleanup_fn_func_get_all_categories($0
    )
})
}
/**
 * Get all rule info for a language
 */
public func getAllRules(language: Language) -> [RuleInfo] {
    return try!  FfiConverterSequenceTypeRuleInfo.lift(try! rustCall() {
    uniffi_yooz_text_cleanup_fn_func_get_all_rules(
        FfiConverterTypeLanguage.lower(language),$0
    )
})
}
/**
 * Get available categories for a language (categories that have rules)
 */
public func getAvailableCategoriesForLanguage(language: Language) -> [Category] {
    return try!  FfiConverterSequenceTypeCategory.lift(try! rustCall() {
    uniffi_yooz_text_cleanup_fn_func_get_available_categories_for_language(
        FfiConverterTypeLanguage.lower(language),$0
    )
})
}
/**
 * Get all supported languages
 */
public func getAvailableLanguages() -> [Language] {
    return try!  FfiConverterSequenceTypeLanguage.lift(try! rustCall() {
    uniffi_yooz_text_cleanup_fn_func_get_available_languages($0
    )
})
}
/**
 * Get free tier categories
 */
public func getFreeCategories() -> [Category] {
    return try!  FfiConverterSequenceTypeCategory.lift(try! rustCall() {
    uniffi_yooz_text_cleanup_fn_func_get_free_categories($0
    )
})
}
/**
 * Get currently implemented languages
 */
public func getImplementedLanguages() -> [Language] {
    return try!  FfiConverterSequenceTypeLanguage.lift(try! rustCall() {
    uniffi_yooz_text_cleanup_fn_func_get_implemented_languages($0
    )
})
}
/**
 * Get premium tier categories
 */
public func getPremiumCategories() -> [Category] {
    return try!  FfiConverterSequenceTypeCategory.lift(try! rustCall() {
    uniffi_yooz_text_cleanup_fn_func_get_premium_categories($0
    )
})
}
/**
 * Get pro tier categories
 */
public func getProCategories() -> [Category] {
    return try!  FfiConverterSequenceTypeCategory.lift(try! rustCall() {
    uniffi_yooz_text_cleanup_fn_func_get_pro_categories($0
    )
})
}
/**
 * Get rule count for a language
 */
public func getRuleCount(language: Language) -> UInt32 {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_yooz_text_cleanup_fn_func_get_rule_count(
        FfiConverterTypeLanguage.lower(language),$0
    )
})
}
/**
 * Get rule count for a language and category
 */
public func getRuleCountForCategory(language: Language, category: Category) -> UInt32 {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_yooz_text_cleanup_fn_func_get_rule_count_for_category(
        FfiConverterTypeLanguage.lower(language),
        FfiConverterTypeCategory.lower(category),$0
    )
})
}
/**
 * Get rule info for a category
 */
public func getRulesForCategory(language: Language, category: Category) -> [RuleInfo] {
    return try!  FfiConverterSequenceTypeRuleInfo.lift(try! rustCall() {
    uniffi_yooz_text_cleanup_fn_func_get_rules_for_category(
        FfiConverterTypeLanguage.lower(language),
        FfiConverterTypeCategory.lower(category),$0
    )
})
}
/**
 * Get library version
 */
public func getVersion() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_yooz_text_cleanup_fn_func_get_version($0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_yooz_text_cleanup_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_yooz_text_cleanup_checksum_func_correct_grammar() != 60719) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_yooz_text_cleanup_checksum_func_correct_grammar_for_language() != 31067) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_yooz_text_cleanup_checksum_func_correct_grammar_with_categories() != 16254) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_yooz_text_cleanup_checksum_func_correct_grammar_with_options() != 36360) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_yooz_text_cleanup_checksum_func_get_all_categories() != 56658) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_yooz_text_cleanup_checksum_func_get_all_rules() != 29652) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_yooz_text_cleanup_checksum_func_get_available_categories_for_language() != 43885) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_yooz_text_cleanup_checksum_func_get_available_languages() != 18331) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_yooz_text_cleanup_checksum_func_get_free_categories() != 15288) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_yooz_text_cleanup_checksum_func_get_implemented_languages() != 59163) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_yooz_text_cleanup_checksum_func_get_premium_categories() != 56662) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_yooz_text_cleanup_checksum_func_get_pro_categories() != 24809) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_yooz_text_cleanup_checksum_func_get_rule_count() != 46161) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_yooz_text_cleanup_checksum_func_get_rule_count_for_category() != 48394) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_yooz_text_cleanup_checksum_func_get_rules_for_category() != 45685) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_yooz_text_cleanup_checksum_func_get_version() != 64439) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all